name: DevSecOps CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline-health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Echo Hello DevSecOps
        run: |
          echo "GitHub Actions Pipeline Initialized Successfully!"
          echo "Running on event: ${{ github.event_name }}"
